### ISSUE TITLE
Does not work if Default site is not running on 80 port

### ISSUE THREAD

**Issue by PratikVpel** [duduyoyo/WebSocket4OPC#11]
I do not have 80 port available due to some other service running. I tried to connect use OPC on 8081 port but it does not work like that. There should be an option

**Comment by duduyoyo** [comment]
My app has no idea to default port to use. It simply binds to default web site with any port. What you can do, first browse default web site and make sure you can open it properly in browser as below (your url should be like http://localhost:8081). Then change that url to http://localhost:8081/OPC/websocket.html. If it can display properly, you need configure your firewall to let port 8081 open to remote request. Cheers!

![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/6dc3ebcb-bdfc-493b-a931-c0eac7f58740)
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/4b9cb782-cdaf-41d8-85b5-18ff9ed92337)

**Comment by PratikVpel** [comment]
Hi, Thank you for the response. Inititially it was not working on another port. But, after the restart it started working again
