### ISSUE TITLE
Add OPCPool failed

### ISSUE THREAD

**Issue by minos250** [duduyoyo/WebSocket4OPC#2]
after installation, I found this error Add OPCPool failed
![erreur](https://user-images.githubusercontent.com/56107291/184368279-5a3ed757-fc6f-4455-9a78-089d60b54a87.PNG)

**Comment by duduyoyo** [comment]
You need replace userAccount / userPassword with your own Windows account and password. Meanwhile this account should have administrator privilege since it is used to run in AppPool.

**Comment by minos250** [comment]
thank you I will try and I will return for you

**Comment by minos250** [comment]
ok it work
