### ISSUE TITLE
连接失败

### ISSUE THREAD

**Issue by hg-hyy** [duduyoyo/WebSocket4OPC#4]
我安装之后访问页面显示 DISCONNECTED 是什么问题？ 我在WIN10 LTSC 21H2上测试，Opc Server 是kepware6

**Comment by duduyoyo** [comment]
这里注意二点，一是安装时你的帐号在IIS中是否有合适的权限可以运行app pool，第二是该帐号在opc server中是否有合适的权限去操作。建议在另一台机子或vm上用matrikcon的免费opc server试下

**Comment by hg-hyy** [comment]
![image](https://user-images.githubusercontent.com/17331400/214033413-50a77726-6b86-4639-9ce8-c75aad645eb2.png)
我重新安装了个虚拟机测试ok,仔细对比了下IIS配置是一样的，但是还是不行。

**Comment by duduyoyo** [comment]
根据你的第二个截图，感觉你的实体机的WebSocket功能没有打开，请检查如下图的设置。如还有问题，在EventViewer里请列出OPC WebSocket Native Module里的内容方便我查找原因。你也可以在实体和虚拟机间比较你的设置发现问题。
![image](https://user-images.githubusercontent.com/13662339/214069924-968bd10c-f103-4421-b56d-2916c5f67984.png)

**Comment by hg-hyy** [comment]
功能是打开的，我都是在虚拟机里测试的。
![image](https://user-images.githubusercontent.com/17331400/214222718-b76afd5a-509b-4f20-af3e-14ca37445301.png)
![image](https://user-images.githubusercontent.com/17331400/214222768-2e8060df-3b60-44e6-adf2-f0650f7ca4e2.png)

**Comment by hg-hyy** [comment]
确实如此，感谢

**Comment by duduyoyo** [comment]
在多服务器环境下，现在可以支持你选定的服务器了。只要在config xml文件中把你需要的服务器的ProgID放进去，就可以了。
