### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by zhangzijie-820** [duduyoyo/WebSocket4OPC#6]
**Describe the bug**
i use install.bat username password to install this project. when i use http://localhost/OPC/websocket.html will show 503 service Unavailable. when i go to iis management the OPCPool stop. what should i do for this?

**Comment by duduyoyo** [comment]
It looks like you didn't turn on Web Service from IIS. Check one of closed issues in this section where I have a screen shot of enabling Web Service for IIS. If you still have problems upload your screen shots so I can better troubleshoot it.

**Comment by duduyoyo** [comment]
Here you go, [https://github.com/duduyoyo/WebSocket4OPC/issues/4] issue 4

**Comment by zhangzijie-820** [comment]
I have a solution to solve my question. I change the Application pool identity to local service. it's done. thanks
