### ISSUE TITLE
运行一段时间后，OPCPool中止

### ISSUE THREAD

**Issue by zhangzijie-820** [duduyoyo/WebSocket4OPC#7]
目前遇到一个问题，当这个服务运行一段时间后，IIS服务里面的OPCPool会意外停止，需要手动去重启此服务后才能再继续正常运行，请问您有遇到这个问题吗，需要如何排查意外终止的原因

**Comment by duduyoyo** [comment]
大概过多长时间中止？容易复现吗？在Event Viewer中有什么异常可以附上？

**Comment by zhangzijie-820** [comment]
大概运行半个小时左右或者更久一段时间，时间不定，我在测试中，日志量会很大，会有什么原因造成这个问题吗，Event Viewer的截图如下，但是没有错误详情，
![WechatIMG95](https://github.com/duduyoyo/WebSocket4OPC/assets/58876596/8eebc7f6-841c-4821-9058-dff4a511a06c)

**Comment by zhangzijie-820** [comment]
![WechatIMG96](https://github.com/duduyoyo/WebSocket4OPC/assets/58876596/0b2ab8d1-249c-4939-b662-45d05c8c8797)
不好意思，我似乎找到了详细的日志详情

**Comment by zhangzijie-820** [comment]
![WechatIMG97](https://github.com/duduyoyo/WebSocket4OPC/assets/58876596/68f53fe9-87b0-4f3d-9398-4183cd2ca01b)
我也找到了另外一条有关的错误信息，不知道两者之间的区别，哪一种是会造成OPCPool意外终止的呢

**Comment by duduyoyo** [comment]
那是因为OpcEnum.exe不存在或不能访问。它是基金会的exe，专门根据category（比如DA/HDA/AE的类别）来发现注册的具体服务器。重装一下再试试。

**Comment by zhangzijie-820** [comment]
您的意思是说，可能是OpcEnum.exe服务被异常中止了，导致OPCPool无法发现服务，从而导致OPCPool异常退出是吗？但是为什么手动重启了OPCPool之后，又可以正常运行了？

**Comment by duduyoyo** [comment]
不知道你机子上装的防病毒软件有哪些，觉得此应用可疑，然后中止造成OPCPool异常退出？

**Comment by zhangzijie-820** [comment]
有两套环境，一套是有360，一套是windows defender，我可以尝试先把这两个杀毒软件都关闭掉再尝试下，另外我想请教下您OpcEnum.exe这个服务是opc server端会自己带的吗，在任务管理器里能看到这个服务吗？

**Comment by duduyoyo** [comment]
留个邮箱吧，与本应用无直接关系的我可以回复到邮箱中

**Comment by zhangzijie-820** [comment]
不好意思，需要在打扰下您，上时间运行这个app去订阅来自matrikon opc的OPC AE事件，大概运行一个小时后，就会报如下的错误：Server is disconnected due to time out for your trial. You can relaunch it or purchase a license to avoid disruption， 请问下这个是我使用的OPC AE server有试用限制导致的吗？

**Comment by duduyoyo** [comment]
不是Matricon AE server的限制，而是我的软件试用版上的时间限制。另外一个人也反映appPool停止的问题，那是因为他没有装OpcEnum.exe。你的到底是什么问题？

**Comment by zhangzijie-820** [comment]
我这边还正在排查当中，目前还没找到什么头绪，另外这个软件的正式版本可以在那里获取到呢？

**Comment by duduyoyo** [comment]
你可以邮件询问，websocket4opc@gmail.com

**Comment by duduyoyo** [comment]
有收到回信吗？已有一个星期了
