### ISSUE TITLE
I can't launch the application according to the instructions

### ISSUE THREAD

**Issue by DanilaX1** [duduyoyo/WebSocket4OPC#8]
Good afternoon, Please give me a hint where to follow to get your software working
To test your software, I got a separate machine with Windows 10.
I installed the OPC server there and then followed your instructions.
BUT unfortunately there is no answer in the browser.
Please tell me how to find the error or restart your software
![webfor opc](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/cfaa7ce7-f746-4ea1-ba41-f38407544646)

**Comment by DanilaX1** [comment]
I examined the log and tried to find
![errr1](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/b64cbd96-615a-40b3-85d3-3ed36409ccde)
 several errors. maybe it has something to do with it
![errr2](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/8046cfe9-de91-457a-a32e-d8ce6e34329b)

**Comment by duduyoyo** [comment]
From your last image it seems using DCOM, which isn't related to my app at all. Do you have more than one OPC servers running in the same box? My app assumes only one OPC server in one box only and install my app with it.

**Comment by duduyoyo** [comment]
Also from your http error 401, which is Unauthorized, please check account privilege and make sure it has admin privilege to run appPool.

**Comment by DanilaX1** [comment]
Only 1 OPC server is installed.
I tried to give even more privileges to the user, although this user already had administrator rights.
After reinstalling the service, the process ends unexpectedly.
Tell me what else can I check?
![errr13](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/5e8762eb-61b3-47a9-b607-c5c5c63a119a)

**Comment by duduyoyo** [comment]
Has it worked before? Any other anti-virus/anti-malware besides MS ones installed? Do you have OpcEnum.exe running as Windows service in the same box?

**Comment by DanilaX1** [comment]
Has it worked before? No, I just started trying to configure the system
Any other anti-virus/anti-malware besides MS ones installed?
No, only the standard MS defender. Maybe it needs to be disabled
Do you have OpcEnum.exe running as Windows service in the same box? no, I have not seen such an application, does this component need to be additionally installed?

**Comment by DanilaX1** [comment]
Disabling MS Defender did not help.

**Comment by DanilaX1** [comment]
I'm currently using https://github.com/ya-mouse/openopc
this solution does not require OpcEnum.exe
How to add the OpcEnum.exe service?

**Comment by duduyoyo** [comment]
This OpcEnum.exe is from OPC Foundation, which is used to find each vendor's' OPC server. We need a mechanism to know which vendor's ClsId is so we can use it in application - that is the role OpcEnum.exe plays. Without it no OPC server can work properly. You can copy this exe from another box and add it as a Windows service. Without it my app can't work. OpenOPC doesn't provide it either, usually it comes from vendor's OPC server installation. You need that definitely!

**Comment by DanilaX1** [comment]
Good afternoon friend, I haven't lost hope of launching your application. But so far no results.
I installed OPC Core Components Redistributable. so I can start the EnumOPC service. но   AppPoolID OPCPool 
but OPCPool keeps crashing with ExitCode fffffffe. where else should I look to get your application to work?

**Comment by duduyoyo** [comment]
Can you post screenshots on event viewer by sorting source column when you just launch it? There should be a source for OPC native module. Meanwhile in your browser by pressing F12 entering into debug and checking network, see if there is any message available.

**Comment by duduyoyo** [comment]
Check your IIS C:\inetpub\wwwroot\OPC folder, make sure it matches http://localhost/OPC/websocket.html. Or you can browse websocket.html from IIS Internet manager and launch it from there.

**Comment by DanilaX1** [comment]
![1](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/6359d58b-e613-407c-9a1d-aa50debb1606)
![2](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/c69febdd-7cc0-4edb-8d0c-ec8c3dfd2a73)
![3](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/4eadc4bf-a440-41ba-9311-7712cb573870)
![4](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/7ad2fa56-353c-449b-ab24-93148cb150c5)
![5](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/c8780d2b-c72e-4b46-87ec-02bb1232c890)
![6](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/ab96b846-e80c-4ddf-96d8-494357a5ec59)
![7](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/edf642fe-98e0-46ed-ae4c-c4b24faab270)

**Comment by DanilaX1** [comment]
I found several errors in the event viewer, maybe they are somehow related to my problem. The address http://localhost/OPC/websocket.html also does not work. But if you open file:///C:/inetpub/wwwroot/OPC/websocket.html after a few seconds the DISCONNECTED message appears

**Comment by duduyoyo** [comment]
Check your OpcPool and see if you can start it. If not, it is an authority issue for the account you are using. Meanwhile check your setting as below, see if they are the same.
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/fab2f523-2f24-4ada-b609-a73b32d96aa9)
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/dc5184d1-f69c-4188-906f-260fa3a41034)
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/9f6d96af-f433-4382-af7f-6502a354446e)

**Comment by duduyoyo** [comment]
Make sure OpcEnum.exe is running,
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/13662339/d285d768-73d1-4ed6-ade5-d6e09ee3df3f)

**Comment by duduyoyo** [comment]
You installed OpcEnum.exe after OPC server, so categoryID under OpcEnum might not have OPC server ClsId associated. In this case you need re-register or reinstall OPC server so its ClsId will be correctly listed under categoryID of OpcEnum.

**Comment by DanilaX1** [comment]
Good afternoon, thank you for such high-quality support.
I have 2 news, 1 good and 1 bad
I installed updates on windows. and reinstalled the IIS service.
Now http://localhost/OPC/websocket.html is working
and OPCpool starts.
but it still doesn't work
When I go to the application page the following happens.
1 - Freelance OPC Server (ABB server) Starts automatically.
2 - after about 20 seconds the DISCONNECTED message appears
3 - Freelance OPC Server (ABB server) Closes automatically.
I have new messages in the log

**Comment by DanilaX1** [comment]
![77](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/298c1ff1-bd46-4c09-991f-d417341ed566)
![11](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/0492c639-ed10-4e85-a65c-f44e7bf53212)
![22](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/ee8f07d5-9079-4104-a619-52b197fcf2a9)
![33](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/ad4d9c5d-d040-4f52-bc4e-487a1849c076)
![44](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/6cedd647-ae30-4e12-b437-00dbbaa2578e)
![55](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/ab57fec7-081d-4edf-a47c-9d854577c149)
![66](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/a75c7aed-f0ea-4559-8f62-e9d5f8b2cbb8)

**Comment by duduyoyo** [comment]
Great progress! Log indicates you are using DA/AE, but no HDA - which is totally OK. Can you translate Russian to English for the last error (ReadEntityBody error)?

**Comment by DanilaX1** [comment]
Yes you are right. ABB OPC only has DA and AE and does not have HDA.
The last message is translated as
End of file reached. ReadEntityBody() failed.

**Comment by duduyoyo** [comment]
Send email to websocket4opc@gmail.com and I want you to have a patch to try since I don't have ABB OPC server to test. Thx!

**Comment by DanilaX1** [comment]
I'm sorry, it's my fault. After reinstalling Services, I forgot to check the activation of the Web Socket.
Now AE and DA are working as an ABB server.
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/43824834/65519076-090a-4ab0-9ebb-ade1c2c0320a)
