### ISSUE TITLE
A way to select the OPC server

### ISSUE THREAD

**Issue by ohzak** [duduyoyo/WebSocket4OPC#9]
**Is your feature request related to a problem? Please describe.**
Problem is that i am working with a SCADA software that publish all its items via OPC DA also for internal functionings, futhermore is not possible for me to turn off all the unnecessary (for me) servers but i need to access only one of them

**Describe the solution you'd like**
the possibility to indicate the server i need to communicate with, or a solution to access only the server i need

to tell you something more about my issue, 

i managed to install the server and everything seems to work correctly, 

![Screenshot 2024-01-26 135808](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/3298b9e5-792b-4fff-993e-a10be3d99a33)

the https://localhost/opc.websocket.html loads fine and shows the connected message, 

![Screenshot 2024-01-26 135814](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/f372c50f-436c-4d36-8e13-72b7335eef3c)

but when i try a command nothing happens and after few second the page shows the DISCONNECTED message without giving any kind of error in the console

![Screenshot 2024-01-26 135828](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/9f506985-896c-45ac-9a32-0d24ad56842f)

i am currently working with the GENESIS64 software by Iconics inc. which behaviours as previously mentioned, 

Therefore i think that the issue resides in what youi mentioned somewhere in ISSUE #8 in which you say that the software is mentioned to work on machines which has only a single OPC server installed, 

here's the machine's scenario, i need to connect only to the ICONICS.FwxServerOPC.1 

![Screenshot 2024-01-26 140230](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/f5dd51ad-f5be-418f-bf8d-f913a5ac8011)

also i can give you the Event Viewer's error, if can give you any hint

![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/cdfca12a-5f68-4193-850c-c751ac3ce40b)

**Comment by duduyoyo** [comment]
Can you save your related event viewer log to a file and send to websocket4opc@gmail.com? Thx!

**Comment by duduyoyo** [comment]
I have this configuration feature ready over the weekend. Let me know when you are ready to test. Thx!

**Comment by ohzak** [comment]
hello duduyoyo, thank you very much for the effort, you are a god, i am ready to test in any moment

**Comment by duduyoyo** [comment]
You need send me an email so I can reply back with a new dll to test.

**Comment by ohzak** [comment]
just wrote one

**Comment by duduyoyo** [comment]
Replied with new dll. Good luck!

**Comment by ohzak** [comment]
installed the dll, something seems to work but still getting immediately the disconnected message

here's the logs

![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/b981606f-ac4d-4155-ac0c-f87e51eb8a02)

**Comment by duduyoyo** [comment]
It looks like you have AE server, but don't have x64 proxy dll installed. There is a x64proxy folder in installation, and register x64 AE dll like "regsvr32 opc_aeps.dll" in command line with admin privilege. See if that helps.

**Comment by duduyoyo** [comment]
Do you have AE server running properly in production environment? Or have you ever uninstalled AE server in it? For your test environment, does it have AE server? Is it running properly?

**Comment by ohzak** [comment]
i discovered it was auto selecting another AE server that was not online, i removed the server and the AE error disappeared, but still the w3wp.exe / OPCModule.dll is giving error : 

here you can see that servers selection now happens correctly
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/e6d3a664-4b8b-4546-8580-1b7660811fc2)

but still after launching browse command 
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/a1ca3cef-696b-4692-b889-f574653e6227)

an error is raised (in browser i have the DISCONNECT message)
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/a09e8b52-2985-4378-9272-5cfce37a4fbd)

also a error report  is issued
![image](https://github.com/duduyoyo/WebSocket4OPC/assets/59501022/3f537845-09f6-417f-8eec-bb8f98c37e3a)

attached you can find the report generated by the file 

[Report.txt](https://github.com/duduyoyo/WebSocket4OPC/files/14087347/Report.txt)

**Comment by duduyoyo** [comment]
I sent you an email, please check it.
